name: Build & Test

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET
        uses: actions/setup-dotnet@v1.7.2
        with:
          dotnet-version: 5.0.x
      - name: ReportGenerator
        uses: danielpalme/ReportGenerator-GitHub-Action@4.8.12
      - name: Install dependencies
        run: dotnet restore ./Application
      - name: Build
        run: dotnet build ./Application --configuration Release --no-restore
      - name: Test
        run: dotnet test ./Application --no-restore --verbosity normal
